language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer install

script: phpunit --coverage-text
